/**
 * Curated list of major global startup-hub cities for the Headquarters
 * datalist. Format mirrors the existing "San Francisco, CA" placeholder:
 * US/Canada cities use the state/province abbreviation; the rest use the
 * country name. This is a suggestion list only — free entry is still allowed.
 */
export const CITIES: readonly string[] = [
  // United States
  'San Francisco, CA',
  'Palo Alto, CA',
  'Mountain View, CA',
  'San Jose, CA',
  'Oakland, CA',
  'Los Angeles, CA',
  'Santa Monica, CA',
  'San Diego, CA',
  'New York, NY',
  'Brooklyn, NY',
  'Boston, MA',
  'Cambridge, MA',
  'Seattle, WA',
  'Bellevue, WA',
  'Austin, TX',
  'Dallas, TX',
  'Houston, TX',
  'Chicago, IL',
  'Denver, CO',
  'Boulder, CO',
  'Miami, FL',
  'Atlanta, GA',
  'Washington, DC',
  'Philadelphia, PA',
  'Pittsburgh, PA',
  'Portland, OR',
  'Salt Lake City, UT',
  'Phoenix, AZ',
  'Nashville, TN',
  'Raleigh, NC',
  'Durham, NC',
  'Minneapolis, MN',
  'Detroit, MI',
  'Ann Arbor, MI',
  'Columbus, OH',
  'Las Vegas, NV',
  'Kansas City, MO',
  'Provo, UT',
  // Canada
  'Toronto, Canada',
  'Vancouver, Canada',
  'Montreal, Canada',
  'Ottawa, Canada',
  'Waterloo, Canada',
  'Calgary, Canada',
  'Edmonton, Canada',
  // United Kingdom & Ireland
  'London, UK',
  'Cambridge, UK',
  'Oxford, UK',
  'Manchester, UK',
  'Edinburgh, UK',
  'Bristol, UK',
  'Dublin, Ireland',
  'Cork, Ireland',
  // Europe
  'Berlin, Germany',
  'Munich, Germany',
  'Hamburg, Germany',
  'Frankfurt, Germany',
  'Cologne, Germany',
  'Paris, France',
  'Lyon, France',
  'Amsterdam, Netherlands',
  'Rotterdam, Netherlands',
  'Eindhoven, Netherlands',
  'Brussels, Belgium',
  'Stockholm, Sweden',
  'Gothenburg, Sweden',
  'Copenhagen, Denmark',
  'Oslo, Norway',
  'Helsinki, Finland',
  'Madrid, Spain',
  'Barcelona, Spain',
  'Valencia, Spain',
  'Lisbon, Portugal',
  'Porto, Portugal',
  'Milan, Italy',
  'Rome, Italy',
  'Zurich, Switzerland',
  'Geneva, Switzerland',
  'Lausanne, Switzerland',
  'Vienna, Austria',
  'Prague, Czech Republic',
  'Warsaw, Poland',
  'Kraków, Poland',
  'Wrocław, Poland',
  'Budapest, Hungary',
  'Bucharest, Romania',
  'Sofia, Bulgaria',
  'Athens, Greece',
  'Tallinn, Estonia',
  'Vilnius, Lithuania',
  'Riga, Latvia',
  'Reykjavik, Iceland',
  'Luxembourg, Luxembourg',
  // Middle East & Africa
  'Tel Aviv, Israel',
  'Jerusalem, Israel',
  'Haifa, Israel',
  'Dubai, UAE',
  'Abu Dhabi, UAE',
  'Riyadh, Saudi Arabia',
  'Doha, Qatar',
  'Istanbul, Turkey',
  'Cairo, Egypt',
  'Nairobi, Kenya',
  'Lagos, Nigeria',
  'Cape Town, South Africa',
  'Johannesburg, South Africa',
  'Accra, Ghana',
  'Casablanca, Morocco',
  // Asia
  'Bangalore, India',
  'Mumbai, India',
  'Delhi, India',
  'Gurgaon, India',
  'Hyderabad, India',
  'Pune, India',
  'Chennai, India',
  'Singapore',
  'Tokyo, Japan',
  'Osaka, Japan',
  'Seoul, South Korea',
  'Hong Kong',
  'Beijing, China',
  'Shanghai, China',
  'Shenzhen, China',
  'Hangzhou, China',
  'Guangzhou, China',
  'Taipei, Taiwan',
  'Bangkok, Thailand',
  'Jakarta, Indonesia',
  'Kuala Lumpur, Malaysia',
  'Manila, Philippines',
  'Ho Chi Minh City, Vietnam',
  'Hanoi, Vietnam',
  // Oceania
  'Sydney, Australia',
  'Melbourne, Australia',
  'Brisbane, Australia',
  'Perth, Australia',
  'Auckland, New Zealand',
  'Wellington, New Zealand',
  // Latin America
  'São Paulo, Brazil',
  'Rio de Janeiro, Brazil',
  'Mexico City, Mexico',
  'Guadalajara, Mexico',
  'Buenos Aires, Argentina',
  'Santiago, Chile',
  'Bogotá, Colombia',
  'Medellín, Colombia',
  'Lima, Peru',
  'Montevideo, Uruguay',
  'San José, Costa Rica',
  'Panama City, Panama',
];
