#!/usr/bin/env bash
#
# Regenerates infra/nginx/conf.d/cloudflare-realip.conf from Cloudflare's
# published edge ranges (https://www.cloudflare.com/ips/). They change rarely;
# re-run after Cloudflare announces a change, commit, deploy, reload nginx.
#
# Usage: make nginx-cloudflare-ips
set -euo pipefail

OUT="infra/nginx/conf.d/cloudflare-realip.conf"
CIDR='^[0-9a-fA-F:.]+/[0-9]{1,3}$'

v4="$(curl -fsS --max-time 15 https://www.cloudflare.com/ips-v4)"
v6="$(curl -fsS --max-time 15 https://www.cloudflare.com/ips-v6)"

# Refuse to write a half-empty or garbled list: a missing range would make nginx
# throttle everyone behind that edge as one client.
ranges="$(printf '%s\n%s\n' "$v4" "$v6" | sed '/^[[:space:]]*$/d')"
if [ "$(printf '%s\n' "$ranges" | wc -l)" -lt 10 ] || printf '%s\n' "$ranges" | grep -qvE "$CIDR"; then
  echo "❌ Unexpected response from cloudflare.com/ips — $OUT left unchanged."
  exit 1
fi

{
  cat <<'HEADER'
# Cloudflare → real visitor IP. GENERATED by `make nginx-cloudflare-ips`
# (scripts/cloudflare-ips.sh) — don't edit the list by hand.
#
# When capbase.fyi is proxied through Cloudflare (orange cloud), every request
# reaches nginx from a Cloudflare edge address, so $remote_addr — the key of
# every limit_req zone, X-Real-IP, and through it the API throttler — would be
# Cloudflare's, and each edge's visitors would share one rate-limit bucket.
# The realip module swaps in the visitor's address from CF-Connecting-IP, but
# ONLY for a request whose peer is one of these ranges, so nobody can claim an
# address by sending the header straight to the origin.
#
# Harmless while Cloudflare is off (DNS only, grey cloud): no request comes
# from these ranges and nothing changes. Included at http level (conf.d/*.conf),
# so it covers capbase.conf and glitchtip.conf alike.

HEADER
  printf '%s\n' "$ranges" | sed 's/^/set_real_ip_from /; s/$/;/'
  printf '\nreal_ip_header CF-Connecting-IP;\n'
} > "$OUT"

echo "==> Wrote $OUT ($(printf '%s\n' "$ranges" | wc -l | tr -d ' ') ranges)."
echo "    Commit it, deploy, then reload nginx: docker exec capbase-nginx nginx -s reload"
